image:
  repository: asmnt/telegram-proxy
  tag: latest
#  pullPolicy: IfNotPresent
  pullPolicy: Always

secrets:
  name: telegram-credentials  # ← должен существовать в кластере

service:
  port: 8080

resources:
  requests:
    memory: "24Mi"
    cpu: "10m"
  limits:
    memory: "64Mi"
    cpu: "100m"
