apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: default
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: telegraf
  ports:
    - port: 9273
      targetPort: 9273
